name: vlr
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - anyio=3.5.0=py37h06a4308_0
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h5e8e339_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.2.1=h06a4308_0
  - certifi=2021.10.8=py37h06a4308_2
  - cffi=1.15.0=py37h036bc23_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - configparser=5.2.0=pyhd8ed1ab_0
  - cryptography=36.0.0=py37h9ce1e76_0
  - cudatoolkit=10.2.89=h8f6ccaa_10
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.3=py37_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - importlib-metadata=4.8.2=py37h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py37h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=0.17.0=py_0
  - jpeg=9e=h7f98852_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py37h06a4308_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.10=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1d223b6_14
  - libiconv=1.16=h516909a_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.4=h780b84a_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtiff=4.3.0=h542a066_3
  - libuv=1.43.0=h7f98852_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.3.0=py37h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h9c3ff4c_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.6=he412f7d_0
  - notebook=6.4.8=py37h06a4308_0
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py37h44f0d7a_2
  - pip=22.0.4=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - promise=2.3=py37h89c1867_5
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.19.4=py37hcd2ae1e_0
  - psutil=5.9.0=py37h5e8e339_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37h89c1867_4
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py37h5e8e339_3
  - pyzmq=22.3.0=py37h295c915_2
  - readline=8.1=h46c0cb4_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.7.3=py37hc147768_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sentry-sdk=1.5.7=pyhd8ed1ab_0
  - setproctitle=1.2.2=py37h5e8e339_1
  - setuptools=60.10.0=py37h89c1867_0
  - shortuuid=1.0.8=py37h89c1867_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sniffio=1.2.0=py37h06a4308_1
  - sqlite=3.37.1=h4ff8645_0
  - termcolor=1.1.0=py_2
  - terminado=0.13.1=py37h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.12=h27826a3_0
  - torchvision=0.12.0=py37_cu102
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.1.1=pyha770c72_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wandb=0.12.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37h06a4308_4
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yaspin=2.1.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - astroid==2.9.3
    - beautifulsoup4==4.10.0
    - chardet==4.0.0
    - clean-fid==0.1.22
    - cycler==0.11.0
    - filelock==3.6.0
    - fonttools==4.31.2
    - gdown==4.4.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - idna==2.10
    - install==1.3.5
    - isort==5.10.1
    - kiwisolver==1.4.2
    - lazy-object-proxy==1.7.1
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mccabe==0.6.1
    - platformdirs==2.5.1
    - pylint==2.12.2
    - requests==2.25.1
    - soupsieve==2.3.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - toml==0.10.2
    - tqdm==4.63.0
    - typed-ast==1.5.2
    - werkzeug==2.1.1
    - wrapt==1.13.3